### ISSUE TITLE
PPK compatibility

### ISSUE THREAD

**Issue by kikislater** [ardusimple/simpleRTK2B#1]
Is it possible to do PPK with simpleRTK2B ? 
In other words : does it have memory to stock raw datas ?

**Comment by jolivart** [comment]
Hi @kikislater simpleRTK2B has no internal memory but you can easily connect a data logger to any of the two available UART ports and record raw data.

**Comment by kikislater** [comment]
It's been a long time ... But now with simpleRTK2Blite, is there RX1 and TX1 to connect a data logger ? 
I'm unable to find SimpleRTK2B or simpleRTK2Blite pin out !

**Comment by jolivart** [comment]
Hi @kikislater, you can find the pinout info here
[https://www.ardusimple.com/simplertk2b-hookup-guide/](https://www.ardusimple.com/simplertk2b-hookup-guide/)
and here:
https://www.ardusimple.com/simplertk2blite-hookup-guide/
