### ISSUE TITLE
100% resources used when running simpleRTK2B

### ISSUE THREAD

**Issue by swane** [ardusimple/simpleRTK2B#7]
When run on a Raspberry Pi 3B+ (Stretch OS) using ROS (Kinetic 1.14.3) ,
the application consumes 100% computing power with the Ardusimple hardware connected (dual antenna for heading information).

**Comment by Mac-in-Memphis** [comment]
Hello,I have a Ardusimple simpleRTK2B rover/base pair, with temperamental/fluctuating results.I also have access to a NTRIP Caster (thru a  university login) which has a base station antennae ~10 km from where I’d like to survey a personal worksite. I use an Android OS running SWMaps for determining elevations and Lat/long and data capture. I connect the android to an iPhone hotspot via Bluetooth for my internet connection for the NTrip access.I’m trying the NTrip method; but still doing something wrong. SWMaps doesn’t seem to have the ability to make NTrip connections. :/ Perhaps I need to reconfigure the Rover UBlox firmwhere (I experimented with this about a year ago, but I’m rusty on this); or use an android app (NTrip Client) to send the corrections to the client PRIOR to SWMaps? Do I need to configure SWMaps to see a mock gps signal?Do you have a white paper or diagrams for such a convoluted setup? Any other software suggestions? This is a personal project, and I’m on a budget, so plz let me know my options for using NTrip.Kind Regards,Mac Swope (Near Memphis) West Tennessee, USASent from Swope's iPhoneMobile: 901.484-2274On Jan 30, 2023, at 9:39 AM, Sam Wane ***@***.***> wrote:﻿
Closed #7 as completed.
